name: Save LOF Premium Data

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: '40 6 * * 1-5'
  workflow_dispatch: # 手动触发

jobs:
  save-lof-data:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure data directory exists
      run: mkdir -p data

    - name: Run save_lof_data.py
      run: python save_lof_data.py

    - name: Backup csv to repo data directory
      run: |
        mkdir -p ../data
        cp data/$(date +'%Y%m%d').csv ../data/

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      if: success()  # 仅在脚本成功时上传
      with:
        tag_name: lof-data-${{ github.run_date }}  # 按日期打标签
        files: data/$(date +'%Y%m%d').csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}