name: Save LOF Premium Data

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: '40 6 * * 1-5'
  workflow_dispatch: # 手动触发

permissions:  # 添加权限设置
  contents: write  # 允许推送内容
  pull-requests: write  # 允许创建 PR

jobs:
  save-lof-data:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取所有历史记录，用于commit
        token: ${{ secrets.GITHUB_TOKEN }}  # 关键：使用具有写权限的token

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure data directory exists
      run: mkdir -p data

    - name: Run save_lof_data.py
      run: python save_lof_data.py
      id: run-script  # 添加ID用于后续步骤引用

    - name: Check file existence
      run: |
        if [ -f "data/$(date +'%Y%m%d').csv" ]; then
          echo "HAS_FILE=true" >> $GITHUB_ENV
        else
          echo "HAS_FILE=false" >> $GITHUB_ENV
        fi

    - name: Commit data file
      if: success() && steps.run-script.outcome == 'success' && env.HAS_FILE == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Save LOF data for $(date +'%Y-%m-%d')" || echo "No changes to commit"

    # 使用专门设计的推送action
    - name: Push changes
      if: success() && steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}